### ISSUE TITLE
Update for new powers from Rise of the Underworld patch

### ISSUE THREAD

**Issue by kp-g-mok** [cyclonus101/Lab-of-Legends-Auto-Roller#1]
https://www.reddit.com/r/LegendsOfRuneterra/comments/ob2lmo/this_was_not_in_the_patch_notes_but_new_powers/h3l894o/

The 3 known new powers so far:

Counterfeit Production (Common): Round Start: Create a Fleeting 0 cost Counterfeit Copies in hand.

Lie in Wait (Rare): Allies everywhere that cost 3 or less are Lurkers and have Lurk

Feral Senses (Epic !!!): Round Start: Create a Fleeting Feral Prescience in hand.

**Comment by cyclonus101** [comment]
I'll have an update within 2-3 hours

**Comment by kp-g-mok** [comment]
Awesome, this script has been such a great QoL fix for Lab of Legends

**Comment by cyclonus101** [comment]
Alright finished the update, I did some testing and debugging and it seems everything is working. I've only seen feral senses skipped over one time while testing at 1080p.

It's available now.
